CREATE TABLE IF NOT EXISTS `file_object` (
    `id` BIGINT NOT NULL COMMENT '雪花算法文件对象ID',
    `biz_type` VARCHAR(64) NOT NULL COMMENT '业务类型',
    `biz_id` BIGINT NOT NULL COMMENT '业务ID',
    `original_name` VARCHAR(255) NOT NULL COMMENT '原始文件名',
    `stored_name` VARCHAR(255) NOT NULL COMMENT '存储文件名',
    `storage_path` VARCHAR(512) NOT NULL COMMENT '存储相对路径',
    `storage_provider` VARCHAR(32) NOT NULL DEFAULT 'local' COMMENT '存储提供方',
    `file_size` BIGINT NOT NULL COMMENT '文件大小(字节)',
    `content_type` VARCHAR(128) DEFAULT NULL COMMENT 'MIME类型',
    `file_hash` VARCHAR(128) NOT NULL COMMENT '服务端计算的文件hash',
    `status` TINYINT NOT NULL COMMENT '文件状态 0-初始化 1-ready 2-failed 3-deleted',
    `create_user_id` INT NOT NULL COMMENT '创建人ID',
    `create_time` DATETIME NOT NULL COMMENT '创建时间',
    `update_time` DATETIME NOT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_file_object_biz` (`biz_type`, `biz_id`),
    KEY `idx_file_object_hash_status` (`file_hash`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文件对象表';

CREATE TABLE IF NOT EXISTS `upload_session` (
    `id` BIGINT NOT NULL COMMENT '雪花算法上传会话ID',
    `session_code` VARCHAR(64) NOT NULL COMMENT '上传会话编码',
    `biz_type` VARCHAR(64) NOT NULL COMMENT '业务类型',
    `biz_id` BIGINT NOT NULL COMMENT '业务ID',
    `original_name` VARCHAR(255) NOT NULL COMMENT '原始文件名',
    `expected_size` BIGINT NOT NULL COMMENT '客户端声明的总大小',
    `chunk_size` BIGINT NOT NULL COMMENT '标准分片大小',
    `total_chunks` INT NOT NULL COMMENT '总分片数',
    `uploaded_chunks` INT NOT NULL DEFAULT 0 COMMENT '已上传分片数',
    `client_file_hash` VARCHAR(128) DEFAULT NULL COMMENT '客户端声明的整文件hash',
    `server_file_hash` VARCHAR(128) DEFAULT NULL COMMENT '服务端计算的整文件hash',
    `content_type` VARCHAR(128) DEFAULT NULL COMMENT '客户端MIME类型',
    `status` TINYINT NOT NULL COMMENT '会话状态 0-init 1-uploading 2-merging 3-completed 4-failed 5-canceled 6-expired',
    `temp_dir` VARCHAR(255) NOT NULL COMMENT '临时分片目录',
    `file_object_id` BIGINT DEFAULT NULL COMMENT '关联文件对象ID',
    `complete_retry_count` INT NOT NULL DEFAULT 0 COMMENT '合并重试次数',
    `expire_time` DATETIME NOT NULL COMMENT '会话过期时间',
    `last_chunk_time` DATETIME NOT NULL COMMENT '最后上传分片时间',
    `create_user_id` INT NOT NULL COMMENT '创建人ID',
    `create_time` DATETIME NOT NULL COMMENT '创建时间',
    `update_time` DATETIME NOT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_upload_session_code` (`session_code`),
    KEY `idx_upload_session_user_status` (`create_user_id`, `status`),
    KEY `idx_upload_session_expire` (`expire_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='上传会话表';

CREATE TABLE IF NOT EXISTS `upload_chunk` (
    `id` BIGINT NOT NULL COMMENT '雪花算法分片记录ID',
    `session_id` BIGINT NOT NULL COMMENT '上传会话ID',
    `chunk_index` INT NOT NULL COMMENT '分片序号',
    `chunk_size` BIGINT NOT NULL COMMENT '分片大小',
    `chunk_hash` VARCHAR(128) DEFAULT NULL COMMENT '分片hash',
    `storage_path` VARCHAR(512) NOT NULL COMMENT '临时分片相对路径',
    `status` TINYINT NOT NULL COMMENT '分片状态 0-pending 1-uploaded 2-merged 3-failed',
    `retry_count` INT NOT NULL DEFAULT 0 COMMENT '分片重试次数',
    `upload_time` DATETIME NOT NULL COMMENT '上传时间',
    `create_time` DATETIME NOT NULL COMMENT '创建时间',
    `update_time` DATETIME NOT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_upload_chunk_session_index` (`session_id`, `chunk_index`),
    KEY `idx_upload_chunk_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='上传分片表';
