server:
  port: 9401
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  application:
    name: micro-oauth2-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${OAUTH2_AUTH_DB_URL:jdbc:mysql://127.0.0.1:3306/teach_quality_test}
    username: ${OAUTH2_AUTH_DB_USERNAME:root}
    password: ${OAUTH2_AUTH_DB_PASSWORD:}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:http://127.0.0.1:8848}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    port: ${OAUTH2_AUTH_REDIS_PORT:6379}
    host: ${OAUTH2_AUTH_REDIS_HOST:127.0.0.1}
    password: ${OAUTH2_AUTH_REDIS_PASSWORD:}
security:
  jwt:
    key-store-password: ${JWT_KEYSTORE_PASSWORD:changeit}
    key-pair-alias: ${JWT_KEY_PAIR_ALIAS:jwt}
    key-pair-password: ${JWT_KEY_PAIR_PASSWORD:changeit}
management:
  endpoints:
    web:
      exposure:
        include: "*"
